version: '3.7'
services:
  dev:
    volumes:
      - .:/workspace:cached
    
    environment:
      - GIT_COMMITTER_NAME=${GIT_NAME}
      - GIT_AUTHOR_NAME=${GIT_NAME}
      - GIT_COMMITTER_EMAIL=${GIT_EMAIL}
      - GIT_AUTHOR_EMAIL=${GIT_EMAIL}

    command: /bin/sh -c "while sleep 1000; do :; done"
 